### ISSUE TITLE
Estimativa de custo e tempo

### ISSUE THREAD

**Issue by lucaslop** [UnBArqDsw2020-2/2020.2_G4#11]
## Descrição
 Determinar os custos de produção do software. Além disso, determinar o tempo necessário para desenvolver

## Tarefas

- [x] Determinar através de ferramentes o custo e o tempo para produção do software.
- [x]  Colocar no pages

## Critérios adicionais

- [x] Fazer uma introdução ao item no documento.
- [x] Adiciona controle de versão no documento.
- [x] Adicionar referências no documento.

## Informação adicional

- Nenhum

**Comment by lucaslop** [comment]
Custo finalizado!

**Comment by VictorLeviPeixoto** [comment]
Tempo e esforço também, segue o PR #17
