### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by VictorLeviPeixoto** [UnBArqDsw2020-2/2020.2_G4#3]
## Descrição

Gerar a maior quantidade de requisitos para a aplicação com toda a equipe junta

## Tarefas

- [x] Gravar a reunião realizando o brainstorming
- [x] Gerar um documento com todos os requisitos levantados na reunião

## Critérios adicionais

Não possui

## Informação adicional

Gerar o documento no word de preferência.

**Comment by lucaslop** [comment]
Documentado e priorizado todos  os requisitos
