### ISSUE TITLE
Segunda Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2020-2/2020.2_G4#38]
Olá Pessoal!

O Grupo 04 irá avaliar o Grupo 03 nessa segunda avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta entrar no Tópico 2 DSW(Modelagem) da trilha do Moodle, e procurar por "Segunda Avaliação por Pares".

Atenciosamente.

**Comment by VictorLeviPeixoto** [comment]
[Segunda-Avaliação-Por-Pares-04-03.pdf](https://github.com/UnBArqDsw2020-2/2020.2_G4/files/6130810/Segunda-Avaliacao-Por-Pares-04-03.pdf)

Boa tarde professora!

Avaliação feita, segue o PDF
