### ISSUE TITLE
Padrão Singleton

### ISSUE THREAD

**Issue by lucaslop** [UnBArqDsw2020-2/2020.2_G4#51]
## Descrição

Explicar e mostrar a aplicação do projeto singleton

## Tarefas

- [x] Deverá explicar os principais conceitos  do padrão singleton
- [x] Deverá contextualizar de acordo com o projeto
- [x] Deverá mostrar a aplicação no código

**Comment by VictorLeviPeixoto** [comment]
Fechada com o PR #56
