### ISSUE TITLE
Terceira Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2020-2/2020.2_G4#54]
Olá Pessoal!

O Grupo 04 irá avaliar o Grupo 06 nessa terceira avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta entrar no Tópico 2 DSW(Padrões de Projeto) da trilha do Moodle, e procurar por "Terceira Avaliação por Pares".

Atenciosamente.

**Comment by VictorLeviPeixoto** [comment]
Segue o documento com a avaliação do grupo 06
[Critérios - Terceira Avaliação Por Pares - DOC.pdf](https://github.com/UnBArqDsw2020-2/2020.2_G4/files/6298467/Criterios.-.Terceira.Avaliacao.Por.Pares.-.DOC.pdf)
