### ISSUE TITLE
Quarta Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2020-2/2020.2_G4#64]
Olá Pessoal!

O Grupo 04 irá avaliar o Grupo 02 nessa quarta avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta entrar no Tópico 3: Arquitetura e Reutilização de Software do Moodle, e procurar por "Quarta Avaliação por Pares".

Atenciosamente.

**Comment by VictorLeviPeixoto** [comment]
Grupo avaliado de acordo com o documento em anexo
[Quarta-Avaliação-Por-Pares-04-02.pdf](https://github.com/UnBArqDsw2020-2/2020.2_G4/files/6443112/Quarta-Avaliacao-Por-Pares-04-02.pdf)
