### ISSUE TITLE
Rich Picture

### ISSUE THREAD

**Issue by lucaslop** [UnBArqDsw2020-2/2020.2_G4#9]
## Descrição

Criar  rich picture para demonstrar visualmente o escopo do projeto e com o que ele se encaixa.

Descreva a tarefa aqui

## Tarefas

- [x] Criar o rich picture
- [x] Colocar no pages

## Critérios adicionais

- [x] Fazer uma introdução ao item no documento.
- [x] Adiciona controle de versão no documento.
- [x] Adicionar referências no documento.

## Informação adicional

Sugestão:  utilizar o draw.io

**Comment by muriloschiler** [comment]
Done
